<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_01L2IBPpEeytM5_lJyh0oQ" name="EjecucionTelemercadeo" author="Javier Lozano" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_01L2IRPpEeytM5_lJyh0oQ" name="Ejecución de telemercadeo">
      <elements xmi:type="process:Lane" xmi:id="_01L2IhPpEeytM5_lJyh0oQ" name="Asesor Comercial" actor="_01L2OxPpEeytM5_lJyh0oQ">
        <elements xmi:type="process:StartEvent" xmi:id="_01L2IxPpEeytM5_lJyh0oQ" name="Actividad Comercial" outgoing="_01L2OBPpEeytM5_lJyh0oQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_01L2JBPpEeytM5_lJyh0oQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_01L2JRPpEeytM5_lJyh0oQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_01L2JhPpEeytM5_lJyh0oQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_01L2JxPpEeytM5_lJyh0oQ" name="Consultar datos del prospecto en el CRM y contactarlo vía telefónica" outgoing="_wgq5ABUSEeybM7SAJDSYyw" incoming="_01L2OBPpEeytM5_lJyh0oQ" overrideActorsOfTheLane="false" priority="3">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_01L2KBPpEeytM5_lJyh0oQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_01L2KRPpEeytM5_lJyh0oQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_01L2KhPpEeytM5_lJyh0oQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_zx3UgBb1EeyRxr75KeBNDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_zx3UgRb1EeyRxr75KeBNDg" name="actividadComercial" content="actividadComercial" type="TYPE_VARIABLE" returnType="com.company.model.ActividadComercial">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_zx3Ughb1EeyRxr75KeBNDg" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_zx3Ugxb1EeyRxr75KeBNDg" name="registroActividad.nombres" content="registroActividad?.nombres" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_zx3UhBb1EeyRxr75KeBNDg" name="registroActividad" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_zx3UhRb1EeyRxr75KeBNDg" type="JAVA_METHOD" expression="setNombres">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_zx3Uhhb1EeyRxr75KeBNDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_zx3Uhxb1EeyRxr75KeBNDg" name="actividadComercial" content="actividadComercial" type="TYPE_VARIABLE" returnType="com.company.model.ActividadComercial">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_zx3UiBb1EeyRxr75KeBNDg" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_zx3UiRb1EeyRxr75KeBNDg" name="registroActividad.apellidos" content="registroActividad?.apellidos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_zx3Uihb1EeyRxr75KeBNDg" name="registroActividad" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_zx3Uixb1EeyRxr75KeBNDg" type="JAVA_METHOD" expression="setApellidos">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_zx3UjBb1EeyRxr75KeBNDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_zx3UjRb1EeyRxr75KeBNDg" name="actividadComercial" content="actividadComercial" type="TYPE_VARIABLE" returnType="com.company.model.ActividadComercial">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_zx3Ujhb1EeyRxr75KeBNDg" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_zx3Ujxb1EeyRxr75KeBNDg" name="registroActividad.fechaNacimiento" content="registroActividad?.fechaNacimiento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_zx3UkBb1EeyRxr75KeBNDg" name="registroActividad" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_zx3UkRb1EeyRxr75KeBNDg" type="JAVA_METHOD" expression="setFechaNacimiento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_zx3Ukhb1EeyRxr75KeBNDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_zx3Ukxb1EeyRxr75KeBNDg" name="actividadComercial" content="actividadComercial" type="TYPE_VARIABLE" returnType="com.company.model.ActividadComercial">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_zx3UlBb1EeyRxr75KeBNDg" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_zx3UlRb1EeyRxr75KeBNDg" name="registroActividad.sexo" content="registroActividad?.sexo" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_zx3Ulhb1EeyRxr75KeBNDg" name="registroActividad" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_zx3Ulxb1EeyRxr75KeBNDg" type="JAVA_METHOD" expression="setSexo">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_zx3UmBb1EeyRxr75KeBNDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_zx3UmRb1EeyRxr75KeBNDg" name="actividadComercial" content="actividadComercial" type="TYPE_VARIABLE" returnType="com.company.model.ActividadComercial">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_zx3Umhb1EeyRxr75KeBNDg" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_zx3Umxb1EeyRxr75KeBNDg" name="registroActividad.respuestaCliente" content="registroActividad?.respuestaCliente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_zx3UnBb1EeyRxr75KeBNDg" name="registroActividad" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_zx3UnRb1EeyRxr75KeBNDg" type="JAVA_METHOD" expression="setRespuestaCliente">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_01L2KxPpEeytM5_lJyh0oQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_01L2LBPpEeytM5_lJyh0oQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_01L2LRPpEeytM5_lJyh0oQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_01L2LhPpEeytM5_lJyh0oQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_01L2LxPpEeytM5_lJyh0oQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_01L2MBPpEeytM5_lJyh0oQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_34nugBb1EeyRxr75KeBNDg" name="consultarCRM" content="35d2298b-c016-45d6-879e-6c3e0bfc4f98" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_01L2MhPpEeytM5_lJyh0oQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_zx2tcBb1EeyRxr75KeBNDg" name="registroActividad" type="COMPLEX" dataReference="actividadComercial" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_zx2tcRb1EeyRxr75KeBNDg" name="nombres" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_zx2tchb1EeyRxr75KeBNDg" name="apellidos" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_zx2tcxb1EeyRxr75KeBNDg" name="fechaNacimiento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_zx2tdBb1EeyRxr75KeBNDg" name="sexo" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_zx2tdRb1EeyRxr75KeBNDg" name="respuestaCliente" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_01L2MxPpEeytM5_lJyh0oQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_yEbKwBUSEeybM7SAJDSYyw" name="Registrar la interacción no interes en el CRM" outgoing="_hpU00BUTEeybM7SAJDSYyw" incoming="_yEfcMBUSEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yEbKwhUSEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yEbKwRUSEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yEbKwxUSEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_yEbKxBUSEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_yEbKxRUSEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_yEbKxhUSEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_yEbKyBUSEeybM7SAJDSYyw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_yEbKxxUSEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_zC3wABUSEeybM7SAJDSYyw" name="Registrar la interacción no contesta en el CRM" outgoing="_g7naQBUTEeybM7SAJDSYyw" incoming="_zC-dsBUSEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zC4XERUSEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zC4XEBUSEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zC4XEhUSEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_zC4XExUSEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_zC4XFBUSEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_zC4XFRUSEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_zC4XFxUSEeybM7SAJDSYyw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_zC4XFhUSEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_RBkYYBUTEeybM7SAJDSYyw" name="Respuesta del cliente" outgoing="_xGe70BUSEeybM7SAJDSYyw _yEfcMBUSEeybM7SAJDSYyw _zC-dsBUSEeybM7SAJDSYyw" incoming="_wgq5ABUSEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wggg8RUSEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wggg8BUSEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wggg8hUSEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_jMge0BUTEeybM7SAJDSYyw" documentation="Motor de reglas" name="Consultar viabilidad del traslado" outgoing="_oPakgBXCEeybM7SAJDSYyw" incoming="_xGe70BUSEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jMge0hUTEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jMge0RUTEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jMge0xUTEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jMge1BUTEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jMge1RUTEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jMge1hUTEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jMge2BUTEeybM7SAJDSYyw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jMge1xUTEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_w8pP0BXBEeybM7SAJDSYyw" name="Cliente no pudo ser contactado" incoming="_g7naQBUTEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_g7ihwRUTEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_g7ihwBUTEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_g7ihwhUTEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_xU3ikBXBEeybM7SAJDSYyw" name="Cliente no demuestra interés" incoming="_hpU00BUTEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hpRKcRUTEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hpRKcBUTEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hpRKchUTEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_0zeFgBXDEeybM7SAJDSYyw" name="Resultado de viabilidad" outgoing="_Ul0SQBXDEeybM7SAJDSYyw _7kRD4BXDEeybM7SAJDSYyw _DgnPYBXEEeybM7SAJDSYyw _Up4dcBXEEeybM7SAJDSYyw" incoming="_oPakgBXCEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oPW6IhXCEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oPW6IRXCEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oPW6IxXCEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Dgi98BXEEeybM7SAJDSYyw" name="Notificar al cliente la restricción que tiene y registrar la interacción en el CRM" outgoing="_SUwZIBXEEeybM7SAJDSYyw" incoming="_DgnPYBXEEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DgjlARXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DgjlABXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DgjlAhXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_DgjlAxXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_DgjlBBXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_DgjlBRXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_DgjlBxXEEeybM7SAJDSYyw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_DgjlBhXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_SUsHsBXEEeybM7SAJDSYyw" name="Cliente en listas restrictivas" incoming="_SUwZIBXEEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SUsuwRXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SUsuwBXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SUsuwhXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Up0zEBXEEeybM7SAJDSYyw" name="Indicar al cliente la no viabilidad y registrar en el CRM la novedad de futuro prospecto" outgoing="_jFd9QBXEEeybM7SAJDSYyw" incoming="_Up4dcBXEEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Up0zEhXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Up0zERXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Up0zExXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Up0zFBXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Up0zFRXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Up0zFhXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Up1aIRXEEeybM7SAJDSYyw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Up1aIBXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_jFZr0BXEEeybM7SAJDSYyw" name="Genera Oportunidad  a largo plazo" incoming="_jFd9QBXEEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jFZr0hXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jFZr0RXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jFZr0xXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_9ugRYBXEEeybM7SAJDSYyw" name="Transferir llamada a  LSC para asignación de cita de doble asesoría en oficina" outgoing="_-K1BABXEEeybM7SAJDSYyw" incoming="_Ul0SQBXDEeybM7SAJDSYyw" outgoingMessages="_XCQ0oBXFEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vnn2QRXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vnn2QBXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vnn2QhXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_vnn2QxXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_vnn2RBXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_vnn2RRXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_vnn2RxXEEeybM7SAJDSYyw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_vnn2RhXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_XCL8IBXFEeybM7SAJDSYyw" name="Validar doble Asesoria">
            <correlation xmi:type="process:Correlation" xmi:id="_XCL8IRXFEeybM7SAJDSYyw">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_XCL8IhXFEeybM7SAJDSYyw"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_XCL8IxXFEeybM7SAJDSYyw" name="Doble Asesoría" content="Doble Asesoría" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_XCL8JBXFEeybM7SAJDSYyw" name="Validar doble asesoría" content="Validar doble asesoría" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_XCL8JRXFEeybM7SAJDSYyw">
              <expressions xmi:type="expression:ListExpression" xmi:id="_X1rjsBXHEeybM7SAJDSYyw">
                <expressions xmi:type="expression:Expression" xmi:id="_X1rjsRXHEeybM7SAJDSYyw" name="actividadComercial" content="actividadComercial" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_X1rjshXHEeybM7SAJDSYyw" name="actividadComercial" content="actividadComercial" interpreter="GROOVY" type="TYPE_VARIABLE" returnType="com.company.model.ActividadComercial">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_jOoGABXUEeybM7SAJDSYyw" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
                </expressions>
              </expressions>
            </messageContent>
          </events>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_-fYUsBXEEeybM7SAJDSYyw" name="Recibir resultado doble asesoría" outgoing="_MeHm0BXNEeybM7SAJDSYyw" incoming="_-K1BABXEEeybM7SAJDSYyw" event="Resultado doble asesoría" incomingMessag="_p1wI0BXFEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-KxWoRXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-KxWoBXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-KxWohXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-KxWoxXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-KxWpBXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-KxWpRXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-KxWpxXEEeybM7SAJDSYyw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-KxWphXEEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <correlation xmi:type="expression:TableExpression" xmi:id="_htV3QBXFEeybM7SAJDSYyw"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Na-3sBXNEeybM7SAJDSYyw" name="Doble asesoría Favorece RPM" incoming="_NbDJIBXNEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Na_ewRXNEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Na_ewBXNEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Na_ewhXNEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Pik2UBXNEeybM7SAJDSYyw" name="Resultado de doble asesoría" outgoing="_NbDJIBXNEeybM7SAJDSYyw _QEDywBXNEeybM7SAJDSYyw" incoming="_MeHm0BXNEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MeDVYhXNEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MeDVYRXNEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MeDVYxXNEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_x2ymEBXQEeybM7SAJDSYyw" name="Dar a conocer al cliente las diferentes alternativas para iniciar el proceso de traslado." outgoing="_3xSU8BXYEeybM7SAJDSYyw" incoming="_7kRD4BXDEeybM7SAJDSYyw _QEDywBXNEeybM7SAJDSYyw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7kNZghXDEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7kNZgRXDEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7kNZgxXDEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_R6-W8BcTEeyRxr75KeBNDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_R6-W8RcTEeyRxr75KeBNDg" name="actividadComercial" content="actividadComercial" type="TYPE_VARIABLE" returnType="com.company.model.ActividadComercial">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_R6-W8hcTEeyRxr75KeBNDg" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_R6-W8xcTEeyRxr75KeBNDg" name="registroActividad.alternativaSeleccionada" content="registroActividad?.alternativaSeleccionada" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_R6-W9BcTEeyRxr75KeBNDg" name="registroActividad" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_R6-W9RcTEeyRxr75KeBNDg" type="JAVA_METHOD" expression="setAlternativaSeleccionada">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_7kNZhBXDEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_7kNZhRXDEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_7kNZhhXDEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_7kNZiBXDEeybM7SAJDSYyw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_7kNZhxXDEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_x21CWRXQEeybM7SAJDSYyw" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_x21CWhXQEeybM7SAJDSYyw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_x21CWBXQEeybM7SAJDSYyw">
            <inputs xmi:type="process:ContractInput" xmi:id="_R69v4BcTEeyRxr75KeBNDg" name="registroActividad" type="COMPLEX" dataReference="actividadComercial" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_R69v4RcTEeyRxr75KeBNDg" name="alternativaSeleccionada" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_x21CWxXQEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_8jqe0BXYEeybM7SAJDSYyw" name="Asesorar al cliente en el traslado electrónico y registrar en CRM la oportunidad de venta" outgoing="_J5G18BXZEeybM7SAJDSYyw" incoming="_5J34gBXYEeybM7SAJDSYyw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5J0OIRXYEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5J0OIBXYEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5J0OIhXYEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_zxJbohcdEeyRxr75KeBNDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_zxJboxcdEeyRxr75KeBNDg" name="actividadComercial" content="actividadComercial" type="TYPE_VARIABLE" returnType="com.company.model.ActividadComercial">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_zxJbpBcdEeyRxr75KeBNDg" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_zxJbpRcdEeyRxr75KeBNDg" name="actividadComercialInput.solicitudInmediata" content="actividadComercialInput?.solicitudInmediata" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_zxJbphcdEeyRxr75KeBNDg" name="actividadComercialInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_zxJbpxcdEeyRxr75KeBNDg" type="JAVA_METHOD" expression="setSolicitudInmediata">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5J0OIxXYEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5J0OJBXYEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5J0OJRXYEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5J0OJxXYEeybM7SAJDSYyw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5J0OJhXYEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_8jrF6RXYEeybM7SAJDSYyw">
            <targetForm xmi:type="expression:Expression" xmi:id="_1yb98BcdEeyRxr75KeBNDg" name="asesorarTraslado" content="963fbe2f-d0bb-4ffd-a0fa-390a87f5658f" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_8jrF6BXYEeybM7SAJDSYyw">
            <inputs xmi:type="process:ContractInput" xmi:id="_zxJboBcdEeyRxr75KeBNDg" name="actividadComercialInput" type="COMPLEX" dataReference="actividadComercial" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_zxJboRcdEeyRxr75KeBNDg" name="solicitudInmediata" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_8jrF6xXYEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_EvWG0BXZEeybM7SAJDSYyw" name="Agendar visita" outgoing="_HSW2IBXZEeybM7SAJDSYyw" incoming="_58sckBXYEeybM7SAJDSYyw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_58oLIRXYEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_58oLIBXYEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_58oLIhXYEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_58oLIxXYEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_58oLJBXYEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_58oLJRXYEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_58oLJxXYEeybM7SAJDSYyw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_58oLJhXYEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_EvWt6RXZEeybM7SAJDSYyw">
            <targetForm xmi:type="expression:Expression" xmi:id="_9QiHMBcdEeyRxr75KeBNDg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_EvWt6BXZEeybM7SAJDSYyw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_EvWt6xXZEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_HSSksBXZEeybM7SAJDSYyw" name="Visita agendada" incoming="_HSW2IBXZEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HSSkshXZEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HSSksRXZEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HSSksxXZEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_PRdasBXZEeybM7SAJDSYyw" name="Genera oportunidad a corto plazo" incoming="_PRhFEBXZEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PRdashXZEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PRdasRXZEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PRdasxXZEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_B3J8QBXaEeybM7SAJDSYyw" name="Alternativa Seleccionada" outgoing="_5J34gBXYEeybM7SAJDSYyw _58sckBXYEeybM7SAJDSYyw" incoming="_3xSU8BXYEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3xODghXYEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3xODgRXYEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3xODgxXYEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_LSGMsBXaEeybM7SAJDSYyw" name="¿Cliente desea registrar solicitud de inmediato?" outgoing="_PRhFEBXZEeybM7SAJDSYyw _6LfREBXZEeybM7SAJDSYyw" incoming="_J5G18BXZEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_J5CkgRXZEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_J5CkgBXZEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_J5CkghXZEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_pvArYBY4EeybM7SAJDSYyw" name="Traslado Electrónico Asistido" outgoing="_Qn83EBXaEeybM7SAJDSYyw" incoming="_6LfREBXZEeybM7SAJDSYyw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6La_ohXZEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6La_oRXZEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6La_oxXZEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_xZ4CQBcdEeyRxr75KeBNDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xZ4CQRcdEeyRxr75KeBNDg" name="actividadComercial" content="actividadComercial" type="TYPE_VARIABLE" returnType="com.company.model.ActividadComercial">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xZ4CQhcdEeyRxr75KeBNDg" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xZ4CQxcdEeyRxr75KeBNDg" name="registroActividad.solicitudRegistrada" content="registroActividad?.solicitudRegistrada" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xZ4CRBcdEeyRxr75KeBNDg" name="registroActividad" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xZ4CRRcdEeyRxr75KeBNDg" type="JAVA_METHOD" expression="setSolicitudRegistrada">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6La_pBXZEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6La_pRXZEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6La_phXZEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_6La_qBXZEeybM7SAJDSYyw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_6La_pxXZEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_pvDuuRY4EeybM7SAJDSYyw">
            <targetForm xmi:type="expression:Expression" xmi:id="_4u1doBcdEeyRxr75KeBNDg" name="trasladoAsistido" content="8fa46be8-5034-4af6-9493-77c19c685d5e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_pvDuuBY4EeybM7SAJDSYyw">
            <inputs xmi:type="process:ContractInput" xmi:id="_xZ3bMBcdEeyRxr75KeBNDg" name="registroActividad" type="COMPLEX" dataReference="actividadComercial" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_xZ3bMRcdEeyRxr75KeBNDg" name="solicitudRegistrada" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_pvDuuxY4EeybM7SAJDSYyw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Qn5MsBXaEeybM7SAJDSYyw" name="Solicitud de traslado registrada" incoming="_Qn83EBXaEeybM7SAJDSYyw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Qn5MshXaEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Qn5MsRXaEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Qn5MsxXaEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_QzMoQBafEeyRxr75KeBNDg" name="asesorAsignado" definitionId="bonita-actorfilter-single-user" definitionVersion="1.0.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_QzMoQRafEeyRxr75KeBNDg" definitionId="bonita-actorfilter-single-user" version="1.0.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QzMoQhafEeyRxr75KeBNDg" key="userId">
              <expression xmi:type="expression:Expression" xmi:id="_QzMoQxafEeyRxr75KeBNDg" name="userId()" content="def user = apiAccessor.getIdentityAPI().getUserByUserName(actividadComercial.aliasAsesor);&#xD;&#xA;return user.id;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long" returnTypeFixed="true">
                <referencedElements xmi:type="expression:Expression" xmi:id="_QzMoRBafEeyRxr75KeBNDg" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="org.bonitasoft.engine.api.APIAccessor"/>
                <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QzMoRRafEeyRxr75KeBNDg" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
              </expression>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_c8D7wBXUEeybM7SAJDSYyw" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial">
        <defaultValue xmi:type="expression:Expression" xmi:id="_c8D7wRXUEeybM7SAJDSYyw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_01L2NBPpEeytM5_lJyh0oQ" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_azDtEhXCEeybM7SAJDSYyw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_01L2NhPpEeytM5_lJyh0oQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_01L2NxPpEeytM5_lJyh0oQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_01L2OBPpEeytM5_lJyh0oQ" target="_01L2JxPpEeytM5_lJyh0oQ" source="_01L2IxPpEeytM5_lJyh0oQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_01L2ORPpEeytM5_lJyh0oQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_01L2OhPpEeytM5_lJyh0oQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wgq5ABUSEeybM7SAJDSYyw" target="_RBkYYBUTEeybM7SAJDSYyw" source="_01L2JxPpEeytM5_lJyh0oQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wgrgEBUSEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_wgrgERUSEeybM7SAJDSYyw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xGe70BUSEeybM7SAJDSYyw" name="Demuestra interés" target="_jMge0BUTEeybM7SAJDSYyw" source="_RBkYYBUTEeybM7SAJDSYyw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xGe70RUSEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_xGe70hUSEeybM7SAJDSYyw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yEfcMBUSEeybM7SAJDSYyw" name="No muestra interés" target="_yEbKwBUSEeybM7SAJDSYyw" source="_RBkYYBUTEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yEfcMRUSEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_yEfcMhUSEeybM7SAJDSYyw" name="respuestaNoInteres()" content="actividadComercial.respuestaCliente == &quot;No muestra interés&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QKxuMBcfEeyRxr75KeBNDg" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zC-dsBUSEeybM7SAJDSYyw" name="No contesta" target="_zC3wABUSEeybM7SAJDSYyw" source="_RBkYYBUTEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zC-dsRUSEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_zC-dshUSEeybM7SAJDSYyw" name="respuestaNoContesta()" content="actividadComercial.respuestaCliente == &quot;No contesta&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rZRDIBb7EeyRxr75KeBNDg" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_g7naQBUTEeybM7SAJDSYyw" target="_w8pP0BXBEeybM7SAJDSYyw" source="_zC3wABUSEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_g7naQRUTEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_g7naQhUTEeybM7SAJDSYyw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hpU00BUTEeybM7SAJDSYyw" target="_xU3ikBXBEeybM7SAJDSYyw" source="_yEbKwBUSEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hpU00RUTEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_hpU00hUTEeybM7SAJDSYyw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oPakgBXCEeybM7SAJDSYyw" target="_0zeFgBXDEeybM7SAJDSYyw" source="_jMge0BUTEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oPbLkBXCEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_oPbLkRXCEeybM7SAJDSYyw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ul0SQBXDEeybM7SAJDSYyw" name="Requiere Doble Asesoría" target="_9ugRYBXEEeybM7SAJDSYyw" source="_0zeFgBXDEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ul05UBXDEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ul05URXDEeybM7SAJDSYyw" name="DobleAsesoria" content="DobleAsesoria" interpreter="GROOVY" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7kRD4BXDEeybM7SAJDSYyw" name="Viable" target="_x2ymEBXQEeybM7SAJDSYyw" source="_0zeFgBXDEeybM7SAJDSYyw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7kRD4RXDEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_7kRD4hXDEeybM7SAJDSYyw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DgnPYBXEEeybM7SAJDSYyw" name="Cliente retringido Sarlaft" target="_Dgi98BXEEeybM7SAJDSYyw" source="_0zeFgBXDEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DgnPYRXEEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_DgnPYhXEEeybM7SAJDSYyw" name="Cliente retringido Sarlaft" content="Cliente retringido Sarlaft" interpreter="GROOVY" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SUwZIBXEEeybM7SAJDSYyw" target="_SUsHsBXEEeybM7SAJDSYyw" source="_Dgi98BXEEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SUwZIRXEEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_SUwZIhXEEeybM7SAJDSYyw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Up4dcBXEEeybM7SAJDSYyw" name="No cumple tiempos para traslado" target="_Up0zEBXEEeybM7SAJDSYyw" source="_0zeFgBXDEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Up5EgBXEEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Up5EgRXEEeybM7SAJDSYyw" name="No cumple tiempos para traslado" content="No cumple tiempos para traslado" interpreter="GROOVY" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jFd9QBXEEeybM7SAJDSYyw" target="_jFZr0BXEEeybM7SAJDSYyw" source="_Up0zEBXEEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jFd9QRXEEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_jFd9QhXEEeybM7SAJDSYyw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-K1BABXEEeybM7SAJDSYyw" target="_-fYUsBXEEeybM7SAJDSYyw" source="_9ugRYBXEEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-K1BARXEEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_-K1BAhXEEeybM7SAJDSYyw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MeHm0BXNEeybM7SAJDSYyw" target="_Pik2UBXNEeybM7SAJDSYyw" source="_-fYUsBXEEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MeHm0RXNEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_MeHm0hXNEeybM7SAJDSYyw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NbDJIBXNEeybM7SAJDSYyw" name="Favorece RPM" target="_Na-3sBXNEeybM7SAJDSYyw" source="_Pik2UBXNEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NbDJIRXNEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_NbDJIhXNEeybM7SAJDSYyw" name="FavoreceRPM" content="FavoreceRPM" interpreter="GROOVY" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QEDywBXNEeybM7SAJDSYyw" target="_x2ymEBXQEeybM7SAJDSYyw" source="_Pik2UBXNEeybM7SAJDSYyw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QEDywRXNEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_QEDywhXNEeybM7SAJDSYyw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3xSU8BXYEeybM7SAJDSYyw" target="_B3J8QBXaEeybM7SAJDSYyw" source="_x2ymEBXQEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3xSU8RXYEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_3xSU8hXYEeybM7SAJDSYyw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5J34gBXYEeybM7SAJDSYyw" name="Traslado electrónico" target="_8jqe0BXYEeybM7SAJDSYyw" source="_B3J8QBXaEeybM7SAJDSYyw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5J4fkBXYEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_5J4fkRXYEeybM7SAJDSYyw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_58sckBXYEeybM7SAJDSYyw" name="Visita de asesor" target="_EvWG0BXZEeybM7SAJDSYyw" source="_B3J8QBXaEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_58sckRXYEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_58sckhXYEeybM7SAJDSYyw" name="alternativaVisitar()" content="actividadComercial.alternativaSeleccionada == &quot;Visitar&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_O7ZWgBcKEeyRxr75KeBNDg" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HSW2IBXZEeybM7SAJDSYyw" target="_HSSksBXZEeybM7SAJDSYyw" source="_EvWG0BXZEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HSXdMBXZEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_HSXdMRXZEeybM7SAJDSYyw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_J5G18BXZEeybM7SAJDSYyw" target="_LSGMsBXaEeybM7SAJDSYyw" source="_8jqe0BXYEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_J5G18RXZEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_J5G18hXZEeybM7SAJDSYyw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PRhFEBXZEeybM7SAJDSYyw" name="No" target="_PRdasBXZEeybM7SAJDSYyw" source="_LSGMsBXaEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PRhFERXZEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_PRhFEhXZEeybM7SAJDSYyw" name="solicitudNoInmediata()" content="actividadComercial.solicitudInmediata == 'No'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_fAq2UBcdEeyRxr75KeBNDg" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6LfREBXZEeybM7SAJDSYyw" name="Sí" target="_pvArYBY4EeybM7SAJDSYyw" source="_LSGMsBXaEeybM7SAJDSYyw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6LfRERXZEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_6LfREhXZEeybM7SAJDSYyw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Qn83EBXaEeybM7SAJDSYyw" target="_Qn5MsBXaEeybM7SAJDSYyw" source="_pvArYBY4EeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Qn83ERXaEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Qn83EhXaEeybM7SAJDSYyw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_01L2OxPpEeytM5_lJyh0oQ" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_01L2PBPpEeytM5_lJyh0oQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_01L2PRPpEeytM5_lJyh0oQ">
        <name xmi:type="expression:Expression" xmi:id="_01L2PhPpEeytM5_lJyh0oQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_01L2PxPpEeytM5_lJyh0oQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_01L2QBPpEeytM5_lJyh0oQ">
        <name xmi:type="expression:Expression" xmi:id="_01L2QRPpEeytM5_lJyh0oQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_01L2QhPpEeytM5_lJyh0oQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_01L2QxPpEeytM5_lJyh0oQ">
        <name xmi:type="expression:Expression" xmi:id="_01L2RBPpEeytM5_lJyh0oQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_01L2RRPpEeytM5_lJyh0oQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_01L2RhPpEeytM5_lJyh0oQ">
        <name xmi:type="expression:Expression" xmi:id="_01L2RxPpEeytM5_lJyh0oQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_01L2SBPpEeytM5_lJyh0oQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_01L2SRPpEeytM5_lJyh0oQ">
        <name xmi:type="expression:Expression" xmi:id="_01L2ShPpEeytM5_lJyh0oQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_01L2SxPpEeytM5_lJyh0oQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_N-HlgBXDEeybM7SAJDSYyw" name="Doble Asesoría">
      <elements xmi:type="process:StartMessageEvent" xmi:id="__mJIcBXEEeybM7SAJDSYyw" name="Validar doble asesoría" outgoing="_FGJNUBXFEeybM7SAJDSYyw" event="Validar doble Asesoria" incomingMessag="_XCQ0oBXFEeybM7SAJDSYyw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="__mJIchXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="__mJIcRXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="__mJIcxXEEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndMessageEvent" xmi:id="_GO5lIBXFEeybM7SAJDSYyw" name="Resultado doble asesoría" incoming="_GO92kBXFEeybM7SAJDSYyw" outgoingMessages="_p1wI0BXFEeybM7SAJDSYyw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_GO6MMRXFEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_GO6MMBXFEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_GO6MMhXFEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        <events xmi:type="process:Message" xmi:id="_p1u6sBXFEeybM7SAJDSYyw" name="Resultado doble asesoría">
          <correlation xmi:type="process:Correlation" xmi:id="_p1u6sRXFEeybM7SAJDSYyw">
            <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_p1u6shXFEeybM7SAJDSYyw"/>
          </correlation>
          <targetProcessExpression xmi:type="expression:Expression" xmi:id="_p1u6sxXFEeybM7SAJDSYyw" name="Ejecución de telemercadeo" content="Ejecución de telemercadeo" returnTypeFixed="true"/>
          <targetElementExpression xmi:type="expression:Expression" xmi:id="_p1u6tBXFEeybM7SAJDSYyw" name="Recibir resultado doble asesoría" content="Recibir resultado doble asesoría" returnTypeFixed="true"/>
          <messageContent xmi:type="expression:TableExpression" xmi:id="_p1u6tRXFEeybM7SAJDSYyw">
            <expressions xmi:type="expression:ListExpression" xmi:id="_VyGaABXVEeybM7SAJDSYyw">
              <expressions xmi:type="expression:Expression" xmi:id="_VyGaARXVEeybM7SAJDSYyw" name="actividadComercial" content="actividadComercial" returnTypeFixed="true"/>
              <expressions xmi:type="expression:Expression" xmi:id="_VyGaAhXVEeybM7SAJDSYyw" name="actividadComercial" content="actividadComercial" type="TYPE_VARIABLE" returnType="com.company.model.ActividadComercial">
                <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_VyGaAxXVEeybM7SAJDSYyw" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial"/>
              </expressions>
            </expressions>
          </messageContent>
        </events>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="__H4E0BXUEeybM7SAJDSYyw" name="Procesar doble asesoría" outgoing="_GO92kBXFEeybM7SAJDSYyw" incoming="_FGJNUBXFEeybM7SAJDSYyw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_FGE74hXFEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_FGE74RXFEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_FGE74xXFEeybM7SAJDSYyw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_FGE75BXFEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_FGE75RXFEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_FGE75hXFEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_FGE76BXFEeybM7SAJDSYyw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_FGE75xXFEeybM7SAJDSYyw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_tAsdABXUEeybM7SAJDSYyw" name="actividadComercial" dataType="_01L2VBPpEeytM5_lJyh0oQ" className="com.company.model.ActividadComercial">
        <defaultValue xmi:type="expression:Expression" xmi:id="_tAsdARXUEeybM7SAJDSYyw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_ODChzxXDEeybM7SAJDSYyw" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_oRNy8BXQEeybM7SAJDSYyw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ODCh0RXDEeybM7SAJDSYyw">
        <targetForm xmi:type="expression:Expression" xmi:id="_ODCh0hXDEeybM7SAJDSYyw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FGJNUBXFEeybM7SAJDSYyw" target="__H4E0BXUEeybM7SAJDSYyw" source="__mJIcBXEEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FGJNURXFEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_FGJNUhXFEeybM7SAJDSYyw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GO92kBXFEeybM7SAJDSYyw" target="_GO5lIBXFEeybM7SAJDSYyw" source="__H4E0BXUEeybM7SAJDSYyw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GO92kRXFEeybM7SAJDSYyw"/>
        <condition xmi:type="expression:Expression" xmi:id="_GO92khXFEeybM7SAJDSYyw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_ODCh0xXDEeybM7SAJDSYyw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ODChwBXDEeybM7SAJDSYyw">
        <name xmi:type="expression:Expression" xmi:id="_ODChwRXDEeybM7SAJDSYyw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ODChwhXDEeybM7SAJDSYyw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ODChwxXDEeybM7SAJDSYyw">
        <name xmi:type="expression:Expression" xmi:id="_ODChxBXDEeybM7SAJDSYyw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ODChxRXDEeybM7SAJDSYyw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ODChxhXDEeybM7SAJDSYyw">
        <name xmi:type="expression:Expression" xmi:id="_ODChxxXDEeybM7SAJDSYyw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ODChyBXDEeybM7SAJDSYyw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ODChyRXDEeybM7SAJDSYyw">
        <name xmi:type="expression:Expression" xmi:id="_ODChyhXDEeybM7SAJDSYyw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ODChyxXDEeybM7SAJDSYyw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ODChzBXDEeybM7SAJDSYyw">
        <name xmi:type="expression:Expression" xmi:id="_ODChzRXDEeybM7SAJDSYyw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ODChzhXDEeybM7SAJDSYyw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_01L2TBPpEeytM5_lJyh0oQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_01L2TRPpEeytM5_lJyh0oQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_01L2ThPpEeytM5_lJyh0oQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_01L2TxPpEeytM5_lJyh0oQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_01L2UBPpEeytM5_lJyh0oQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_01L2URPpEeytM5_lJyh0oQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_01L2UhPpEeytM5_lJyh0oQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_01L2UxPpEeytM5_lJyh0oQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_01L2VBPpEeytM5_lJyh0oQ" name="Business_Object"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_XCQ0oBXFEeybM7SAJDSYyw" name="Validar doble Asesoria" target="__mJIcBXEEeybM7SAJDSYyw" source="_9ugRYBXEEeybM7SAJDSYyw"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_p1wI0BXFEeybM7SAJDSYyw" name="Resultado doble asesoría" target="_-fYUsBXEEeybM7SAJDSYyw" source="_GO5lIBXFEeybM7SAJDSYyw"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_01L2VRPpEeytM5_lJyh0oQ" type="Process" element="_01L2IBPpEeytM5_lJyh0oQ" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_01L2VhPpEeytM5_lJyh0oQ" type="2007" element="_01L2IRPpEeytM5_lJyh0oQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_01L2VxPpEeytM5_lJyh0oQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_01L2WBPpEeytM5_lJyh0oQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_01L2WRPpEeytM5_lJyh0oQ" type="3007" element="_01L2IhPpEeytM5_lJyh0oQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_01L2WhPpEeytM5_lJyh0oQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_01L2WxPpEeytM5_lJyh0oQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_01L2XBPpEeytM5_lJyh0oQ" type="3005" element="_01L2JxPpEeytM5_lJyh0oQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_01L2XRPpEeytM5_lJyh0oQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_01L2XhPpEeytM5_lJyh0oQ" x="194" y="236" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_01L2XxPpEeytM5_lJyh0oQ" type="3002" element="_01L2IxPpEeytM5_lJyh0oQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_01L2YBPpEeytM5_lJyh0oQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_01L2YRPpEeytM5_lJyh0oQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_01L2YhPpEeytM5_lJyh0oQ" x="80" y="258"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yEbx0BUSEeybM7SAJDSYyw" type="3027" element="_yEbKwBUSEeybM7SAJDSYyw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_yEbx0hUSEeybM7SAJDSYyw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yEbx0RUSEeybM7SAJDSYyw" x="650" y="122" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zC4-IBUSEeybM7SAJDSYyw" type="3027" element="_zC3wABUSEeybM7SAJDSYyw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zC4-IhUSEeybM7SAJDSYyw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zC4-IRUSEeybM7SAJDSYyw" x="650" y="27" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_RBm0oxUTEeybM7SAJDSYyw" type="3008" element="_RBkYYBUTEeybM7SAJDSYyw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_RBm0pRUTEeybM7SAJDSYyw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_RBnbsBUTEeybM7SAJDSYyw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RBm0pBUTEeybM7SAJDSYyw" x="469" y="254" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jMhF4BUTEeybM7SAJDSYyw" type="3027" element="_jMge0BUTEeybM7SAJDSYyw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jMhF4hUTEeybM7SAJDSYyw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jMhF4RUTEeybM7SAJDSYyw" x="897" y="235" width="148" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_w8rFAxXBEeybM7SAJDSYyw" type="3003" element="_w8pP0BXBEeybM7SAJDSYyw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_w8rsEBXBEeybM7SAJDSYyw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_w8rsERXBEeybM7SAJDSYyw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w8rFBBXBEeybM7SAJDSYyw" x="897" y="50" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xU3ilBXBEeybM7SAJDSYyw" type="3003" element="_xU3ikBXBEeybM7SAJDSYyw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_xU3ilhXBEeybM7SAJDSYyw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_xU3ilxXBEeybM7SAJDSYyw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xU3ilRXBEeybM7SAJDSYyw" x="897" y="145" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0zeskxXDEeybM7SAJDSYyw" type="3008" element="_0zeFgBXDEeybM7SAJDSYyw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0zeslRXDEeybM7SAJDSYyw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0zeslhXDEeybM7SAJDSYyw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0zeslBXDEeybM7SAJDSYyw" x="1175" y="251" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DgkMEBXEEeybM7SAJDSYyw" type="3027" element="_Dgi98BXEEeybM7SAJDSYyw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_DgkMEhXEEeybM7SAJDSYyw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DgkMERXEEeybM7SAJDSYyw" x="1384" y="110" width="180" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SUtV0BXEEeybM7SAJDSYyw" type="3003" element="_SUsHsBXEEeybM7SAJDSYyw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_SUtV0hXEEeybM7SAJDSYyw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SUtV0xXEEeybM7SAJDSYyw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SUtV0RXEEeybM7SAJDSYyw" x="1673" y="140"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Up1aIhXEEeybM7SAJDSYyw" type="3027" element="_Up0zEBXEEeybM7SAJDSYyw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Up2BMBXEEeybM7SAJDSYyw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Up1aIxXEEeybM7SAJDSYyw" x="1384" y="10" width="174" height="87"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jFaS4BXEEeybM7SAJDSYyw" type="3003" element="_jFZr0BXEEeybM7SAJDSYyw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jFaS4hXEEeybM7SAJDSYyw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jFaS4xXEEeybM7SAJDSYyw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jFaS4RXEEeybM7SAJDSYyw" x="1668" y="37"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_9ug4cBXEEeybM7SAJDSYyw" type="3025" element="_9ugRYBXEEeybM7SAJDSYyw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_9ug4chXEEeybM7SAJDSYyw" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9ug4cRXEEeybM7SAJDSYyw" x="1429" y="364" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-fY7wBXEEeybM7SAJDSYyw" type="3026" element="_-fYUsBXEEeybM7SAJDSYyw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-fY7whXEEeybM7SAJDSYyw" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-fY7wRXEEeybM7SAJDSYyw" x="1724" y="368" width="162" height="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NbAF0BXNEeybM7SAJDSYyw" type="3003" element="_Na-3sBXNEeybM7SAJDSYyw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_NbAF0hXNEeybM7SAJDSYyw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_NbAF0xXNEeybM7SAJDSYyw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NbAF0RXNEeybM7SAJDSYyw" x="2151" y="464"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PimrgxXNEeybM7SAJDSYyw" type="3008" element="_Pik2UBXNEeybM7SAJDSYyw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PinSkBXNEeybM7SAJDSYyw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PinSkRXNEeybM7SAJDSYyw" x="94" y="-28"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PimrhBXNEeybM7SAJDSYyw" x="1960" y="388" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_x21pYBXQEeybM7SAJDSYyw" type="3005" element="_x2ymEBXQEeybM7SAJDSYyw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_x21pYhXQEeybM7SAJDSYyw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x21pYRXQEeybM7SAJDSYyw" x="2055" y="226" width="180" height="89"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8jrF7BXYEeybM7SAJDSYyw" type="3005" element="_8jqe0BXYEeybM7SAJDSYyw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_8jrF7hXYEeybM7SAJDSYyw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8jrF7RXYEeybM7SAJDSYyw" x="2588" y="229" width="177" height="88"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EvWt7BXZEeybM7SAJDSYyw" type="3005" element="_EvWG0BXZEeybM7SAJDSYyw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_EvWt7hXZEeybM7SAJDSYyw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EvWt7RXZEeybM7SAJDSYyw" x="2604" y="79" width="116" height="58"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HSTLwBXZEeybM7SAJDSYyw" type="3003" element="_HSSksBXZEeybM7SAJDSYyw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_HSTy0BXZEeybM7SAJDSYyw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_HSTy0RXZEeybM7SAJDSYyw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HSTLwRXZEeybM7SAJDSYyw" x="2835" y="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PReBwBXZEeybM7SAJDSYyw" type="3003" element="_PRdasBXZEeybM7SAJDSYyw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_PReBwhXZEeybM7SAJDSYyw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_PReBwxXZEeybM7SAJDSYyw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PReBwRXZEeybM7SAJDSYyw" x="3120" y="253"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_B3MYgxXaEeybM7SAJDSYyw" type="3008" element="_B3J8QBXaEeybM7SAJDSYyw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_B3M_kBXaEeybM7SAJDSYyw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_B3M_kRXaEeybM7SAJDSYyw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_B3MYhBXaEeybM7SAJDSYyw" x="2403" y="250" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_LSIo8xXaEeybM7SAJDSYyw" type="3008" element="_LSGMsBXaEeybM7SAJDSYyw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_LSJQABXaEeybM7SAJDSYyw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_LSJQARXaEeybM7SAJDSYyw" x="1" y="-58"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LSIo9BXaEeybM7SAJDSYyw" x="2891" y="250" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pvDuvBY4EeybM7SAJDSYyw" type="3005" element="_pvArYBY4EeybM7SAJDSYyw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pvEVwBY4EeybM7SAJDSYyw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pvDuvRY4EeybM7SAJDSYyw" x="3006" y="431" width="119" height="59"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Qn5zwBXaEeybM7SAJDSYyw" type="3003" element="_Qn5MsBXaEeybM7SAJDSYyw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Qn5zwhXaEeybM7SAJDSYyw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Qn5zwxXaEeybM7SAJDSYyw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Qn5zwRXaEeybM7SAJDSYyw" x="3235" y="431"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_01L2YxPpEeytM5_lJyh0oQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_01L2ZBPpEeytM5_lJyh0oQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_01L2ZRPpEeytM5_lJyh0oQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_01L2ZhPpEeytM5_lJyh0oQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_01L2ZxPpEeytM5_lJyh0oQ" x="48" y="10" width="1235" height="550"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_01L2aBPpEeytM5_lJyh0oQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_01L2aRPpEeytM5_lJyh0oQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_01L2ahPpEeytM5_lJyh0oQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_01L2axPpEeytM5_lJyh0oQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_01L2bBPpEeytM5_lJyh0oQ" width="3419" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_ODFlEBXDEeybM7SAJDSYyw" type="2007" element="_N-HlgBXDEeybM7SAJDSYyw">
      <children xmi:type="notation:DecorationNode" xmi:id="_ODFlFRXDEeybM7SAJDSYyw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_ODFlFhXDEeybM7SAJDSYyw" type="7001">
        <children xmi:type="notation:Shape" xmi:id="__mJvgBXEEeybM7SAJDSYyw" type="3012" element="__mJIcBXEEeybM7SAJDSYyw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="__mKWkBXEEeybM7SAJDSYyw" type="5029">
            <layoutConstraint xmi:type="notation:Location" xmi:id="__mKWkRXEEeybM7SAJDSYyw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="__mJvgRXEEeybM7SAJDSYyw" x="1517" y="118"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_GO6zQBXFEeybM7SAJDSYyw" type="3011" element="_GO5lIBXFEeybM7SAJDSYyw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_GO6zQhXFEeybM7SAJDSYyw" type="5028">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_GO6zQxXFEeybM7SAJDSYyw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GO6zQRXFEeybM7SAJDSYyw" x="1813" y="119"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="__H4E2RXUEeybM7SAJDSYyw" type="3027" element="__H4E0BXUEeybM7SAJDSYyw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="__H4r4BXUEeybM7SAJDSYyw" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="__H4E2hXUEeybM7SAJDSYyw" x="1622" y="108" width="116" height="56"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_ODFlERXDEeybM7SAJDSYyw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_ODFlEhXDEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_ODFlExXDEeybM7SAJDSYyw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_ODGMIBXDEeybM7SAJDSYyw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ODFlFBXDEeybM7SAJDSYyw" width="2158" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_01L2bRPpEeytM5_lJyh0oQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_01L2bhPpEeytM5_lJyh0oQ" type="4001" element="_01L2OBPpEeytM5_lJyh0oQ" source="_01L2XxPpEeytM5_lJyh0oQ" target="_01L2XBPpEeytM5_lJyh0oQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_01L2bxPpEeytM5_lJyh0oQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_01L2cBPpEeytM5_lJyh0oQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_01L2cRPpEeytM5_lJyh0oQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_01L2chPpEeytM5_lJyh0oQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wgrgEhUSEeybM7SAJDSYyw" type="4001" element="_wgq5ABUSEeybM7SAJDSYyw" source="_01L2XBPpEeytM5_lJyh0oQ" target="_RBm0oxUTEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wgsHIBUSEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wgsHIRUSEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wgrgExUSEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wgrgFBUSEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xGfi4BUSEeybM7SAJDSYyw" type="4001" element="_xGe70BUSEeybM7SAJDSYyw" source="_RBm0oxUTEeybM7SAJDSYyw" target="_jMhF4BUTEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xGfi4xUSEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xGfi5BUSEeybM7SAJDSYyw" x="-119" y="-17"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xGfi4RUSEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xGfi4hUSEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7Nk78BakEeyRxr75KeBNDg" id="(0.24324324324324326,0.527027027027027)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yEgDQBUSEeybM7SAJDSYyw" type="4001" element="_yEfcMBUSEeybM7SAJDSYyw" source="_RBm0oxUTEeybM7SAJDSYyw" target="_yEbx0BUSEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yEgDQxUSEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yEgDRBUSEeybM7SAJDSYyw" x="37" y="-12"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yEgDQRUSEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yEgDQhUSEeybM7SAJDSYyw" points="[-13, 2, -163, 120]$[-13, -95, -163, 23]$[139, -95, -11, 23]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4WYbkBUTEeybM7SAJDSYyw" id="(0.9534883720930233,0.09302325581395349)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3yNXgBUTEeybM7SAJDSYyw" id="(0.07333333333333333,0.2)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zC-dsxUSEeybM7SAJDSYyw" type="4001" element="_zC-dsBUSEeybM7SAJDSYyw" source="_RBm0oxUTEeybM7SAJDSYyw" target="_zC4-IBUSEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zC_EwhUSEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zC_EwxUSEeybM7SAJDSYyw" x="25" y="44"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zC_EwBUSEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zC_EwRUSEeybM7SAJDSYyw" points="[0, -1, -173, 163]$[0, -164, -173, 0]$[123, -164, -50, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0Dp3kBUSEeybM7SAJDSYyw" id="(0.4883720930232558,0.023255813953488372)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2uX78BUTEeybM7SAJDSYyw" id="(0.03333333333333333,0.17333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_g7oBUBUTEeybM7SAJDSYyw" type="4001" element="_g7naQBUTEeybM7SAJDSYyw" source="_zC4-IBUSEeybM7SAJDSYyw" target="_w8rFAxXBEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_g7oBUxUTEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_g7oBVBUTEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_g7oBURUTEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_g7oBUhUTEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hpVb4BUTEeybM7SAJDSYyw" type="4001" element="_hpU00BUTEeybM7SAJDSYyw" source="_yEbx0BUSEeybM7SAJDSYyw" target="_xU3ilBXBEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hpVb4xUTEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hpVb5BUTEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hpVb4RUTEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hpVb4hUTEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oPbLkhXCEeybM7SAJDSYyw" type="4001" element="_oPakgBXCEeybM7SAJDSYyw" source="_jMhF4BUTEeybM7SAJDSYyw" target="_0zeskxXDEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oPbyoBXCEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oPbyoRXCEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oPbLkxXCEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oPbLlBXCEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Ul05UhXDEeybM7SAJDSYyw" type="4001" element="_Ul0SQBXDEeybM7SAJDSYyw" source="_0zeskxXDEeybM7SAJDSYyw" target="_9ug4cBXEEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ul1gYBXDEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Ul1gYRXDEeybM7SAJDSYyw" x="32" y="-16"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ul05UxXDEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ul05VBXDEeybM7SAJDSYyw" points="[-1, 20, -237, -100]$[-1, 123, -237, 3]$[233, 123, -3, 3]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_N6KgUBXIEeybM7SAJDSYyw" id="(0.01875,0.35)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7kjXwBXDEeybM7SAJDSYyw" type="4001" element="_7kRD4BXDEeybM7SAJDSYyw" source="_0zeskxXDEeybM7SAJDSYyw" target="_x21pYBXQEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7kj-0BXDEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7kj-0RXDEeybM7SAJDSYyw" x="-380" y="-14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7kjXwRXDEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7kjXwhXDEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Dgrg0BXEEeybM7SAJDSYyw" type="4001" element="_DgnPYBXEEeybM7SAJDSYyw" source="_0zeskxXDEeybM7SAJDSYyw" target="_DgkMEBXEEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Dgrg0xXEEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Dgrg1BXEEeybM7SAJDSYyw" x="47" y="-15"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Dgrg0RXEEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Dgrg0hXEEeybM7SAJDSYyw" points="[5, -17, -273, 100]$[5, -128, -273, -11]$[188, -128, -90, -11]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SUxAMBXEEeybM7SAJDSYyw" type="4001" element="_SUwZIBXEEeybM7SAJDSYyw" source="_DgkMEBXEEeybM7SAJDSYyw" target="_SUtV0BXEEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SUxAMxXEEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SUxANBXEEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SUxAMRXEEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SUxAMhXEEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Up99ABXEEeybM7SAJDSYyw" type="4001" element="_Up4dcBXEEeybM7SAJDSYyw" source="_0zeskxXDEeybM7SAJDSYyw" target="_Up1aIhXEEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Up-kEBXEEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Up-kERXEEeybM7SAJDSYyw" x="24" y="74"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Up99ARXEEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Up99AhXEEeybM7SAJDSYyw" points="[0, -21, -274, 201]$[0, -223, -274, -1]$[194, -223, -80, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jFd9QxXEEeybM7SAJDSYyw" type="4001" element="_jFd9QBXEEeybM7SAJDSYyw" source="_Up1aIhXEEeybM7SAJDSYyw" target="_jFaS4BXEEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jFekUBXEEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jFekURXEEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jFd9RBXEEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jFd9RRXEEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-K1oEBXEEeybM7SAJDSYyw" type="4001" element="_-K1BABXEEeybM7SAJDSYyw" source="_9ug4cBXEEeybM7SAJDSYyw" target="_-fY7wBXEEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-K1oExXEEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-K1oFBXEEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-K1oERXEEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-K1oEhXEEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FGJNUxXFEeybM7SAJDSYyw" type="4001" element="_FGJNUBXFEeybM7SAJDSYyw" source="__mJvgBXEEeybM7SAJDSYyw" target="__H4E2RXUEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FGJ0YBXFEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FGJ0YRXFEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FGJNVBXFEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FGJNVRXFEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GO-doBXFEeybM7SAJDSYyw" type="4001" element="_GO92kBXFEeybM7SAJDSYyw" source="__H4E2RXUEeybM7SAJDSYyw" target="_GO6zQBXFEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GO-doxXFEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GO-dpBXFEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GO-doRXFEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GO-dohXFEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XCRbsBXFEeybM7SAJDSYyw" type="4002" element="_XCQ0oBXFEeybM7SAJDSYyw" source="_9ug4cBXEEeybM7SAJDSYyw" target="__mJvgBXEEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XCRbsxXFEeybM7SAJDSYyw" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XCSCwBXFEeybM7SAJDSYyw" x="-220" y="-15"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XCRbsRXFEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XCRbshXFEeybM7SAJDSYyw" points="[9, 34, 0, -254]$[0, 275, -9, -13]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_p1wI0RXFEeybM7SAJDSYyw" type="4002" element="_p1wI0BXFEeybM7SAJDSYyw" source="_GO6zQBXFEeybM7SAJDSYyw" target="_-fY7wBXEEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_p1wv4hXFEeybM7SAJDSYyw" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_p1wv4xXFEeybM7SAJDSYyw" x="-214" y="6"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_p1wv4BXFEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_p1wv4RXFEeybM7SAJDSYyw" points="[-3, -15, 35, 261]$[-34, -240, 4, 36]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MeIN4BXNEeybM7SAJDSYyw" type="4001" element="_MeHm0BXNEeybM7SAJDSYyw" source="_-fY7wBXEEeybM7SAJDSYyw" target="_PimrgxXNEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MeIN4xXNEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MeIN5BXNEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MeIN4RXNEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MeIN4hXNEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NbDwMBXNEeybM7SAJDSYyw" type="4001" element="_NbDJIBXNEeybM7SAJDSYyw" source="_PimrgxXNEeybM7SAJDSYyw" target="_NbAF0BXNEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NbDwMxXNEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NbDwNBXNEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NbDwMRXNEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NbDwMhXNEeybM7SAJDSYyw" points="[-2, 19, -187, -51]$[-2, 67, -187, -3]$[170, 67, -15, -3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QEHdIBXNEeybM7SAJDSYyw" type="4001" element="_QEDywBXNEeybM7SAJDSYyw" source="_PimrgxXNEeybM7SAJDSYyw" target="_x21pYBXQEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QEHdIxXNEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QEHdJBXNEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QEHdIRXNEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QEHdIhXNEeybM7SAJDSYyw" points="[-23, -23, -78, 101]$[-23, -119, -78, 5]$[52, -119, -3, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_QEIrQBXNEeybM7SAJDSYyw" id="(1.0,0.5581395348837209)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_QEIrQRXNEeybM7SAJDSYyw" id="(0.016666666666666666,0.7)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3xS8ABXYEeybM7SAJDSYyw" type="4001" element="_3xSU8BXYEeybM7SAJDSYyw" source="_x21pYBXQEeybM7SAJDSYyw" target="_B3MYgxXaEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3xS8AxXYEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3xS8BBXYEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3xS8ARXYEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3xS8AhXYEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5J4fkhXYEeybM7SAJDSYyw" type="4001" element="_5J34gBXYEeybM7SAJDSYyw" source="_B3MYgxXaEeybM7SAJDSYyw" target="_8jrF7BXYEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5J5GoBXYEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5J5GoRXYEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5J4fkxXYEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5J4flBXYEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_58sckxXYEeybM7SAJDSYyw" type="4001" element="_58sckBXYEeybM7SAJDSYyw" source="_B3MYgxXaEeybM7SAJDSYyw" target="_EvWt7BXZEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_58tDoBXYEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_58tDoRXYEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_58sclBXYEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_58sclRXYEeybM7SAJDSYyw" points="[-1, -20, -231, 147]$[-1, -169, -231, -2]$[180, -169, -50, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HSXdMhXZEeybM7SAJDSYyw" type="4001" element="_HSW2IBXZEeybM7SAJDSYyw" source="_EvWt7BXZEeybM7SAJDSYyw" target="_HSTLwBXZEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HSXdNRXZEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HSYEQBXZEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HSXdMxXZEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HSXdNBXZEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_J5HdABXZEeybM7SAJDSYyw" type="4001" element="_J5G18BXZEeybM7SAJDSYyw" source="_8jrF7BXYEeybM7SAJDSYyw" target="_LSIo8xXaEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_J5HdAxXZEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_J5HdBBXZEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_J5HdARXZEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_J5HdAhXZEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PRhFExXZEeybM7SAJDSYyw" type="4001" element="_PRhFEBXZEeybM7SAJDSYyw" source="_LSIo8xXaEeybM7SAJDSYyw" target="_PReBwBXZEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PRhsIBXZEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PRhsIRXZEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PRhFFBXZEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PRhFFRXZEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6Lf4IBXZEeybM7SAJDSYyw" type="4001" element="_6LfREBXZEeybM7SAJDSYyw" source="_LSIo8xXaEeybM7SAJDSYyw" target="_pvDuvBY4EeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6Lf4IxXZEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6Lf4JBXZEeybM7SAJDSYyw" x="-102" y="-21"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6Lf4IRXZEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6Lf4IhXZEeybM7SAJDSYyw" points="[-3, 18, -156, -171]$[-3, 192, -156, 3]$[94, 192, -59, 3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Qn9eIBXaEeybM7SAJDSYyw" type="4001" element="_Qn83EBXaEeybM7SAJDSYyw" source="_pvDuvBY4EeybM7SAJDSYyw" target="_Qn5zwBXaEeybM7SAJDSYyw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Qn9eIxXaEeybM7SAJDSYyw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Qn9eJBXaEeybM7SAJDSYyw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Qn9eIRXaEeybM7SAJDSYyw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Qn9eIhXaEeybM7SAJDSYyw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
